### ISSUE TITLE
Add config and instructions to README

### ISSUE THREAD

**Issue by sanjarcode** [edmundgentle/wikitime#1]
I was about to write a program just like this.
Can you please add config/running instructions in the README?
Adding *why*, *what*, *how* would really help.

**Comment by edmundgentle** [comment]
Hi Sanjay, I've updated the readme with what I can remember, I hope this helps!
Keep me updated on your progress! 😊

**Comment by sanjarcode** [comment]
Thanks 👍️.

Also, @edmundgentle, my name is 'Sanja**r**', with an R. 
Yeah, I know, Sanjay is a very common Indian name😅️. 
My name's Persian in origin.

**Comment by edmundgentle** [comment]
Hi Sanjar. I'm very sorry about that! I was typing on my phone, and I've just checked, it autocorrected the name, and I forgot to check!

Let me know how you get on with this project, it'd be great to see the final result.

**Comment by sanjarcode** [comment]
Sure, I almost forgot about this.
Ping you when conclusive.
